-- ============================================================
-- 智汇于庄 backend · H2（PostgreSQL 兼容模式）测试表结构
-- 与 src/main/resources/db/schema.sql 语义保持一致，仅做方言裁剪：
--   * 不包含 PostgreSQL 专有的 COMMENT ON 语句；
--   * 标识列 / NUMERIC / TEXT / TIMESTAMP 均被 H2 2.x 原生支持。
-- 全部使用 CREATE TABLE IF NOT EXISTS，保证多测试上下文复用同一
-- 内存库（DB_CLOSE_DELAY=-1）时重复初始化不报错。
-- ============================================================

-- 商品 SKU 与库存（CAS 乐观锁扣减目标表）
CREATE TABLE IF NOT EXISTS t_product_sku (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   VARCHAR(64)  NOT NULL DEFAULT 'global',
    sku_code    VARCHAR(64)  NOT NULL,
    spu_name    VARCHAR(255) NOT NULL,
    price       NUMERIC(12, 2) NOT NULL DEFAULT 0,
    stock       INT          NOT NULL DEFAULT 0,
    version     INT          NOT NULL DEFAULT 0,
    status      VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_t_product_sku_tenant_code UNIQUE (tenant_id, sku_code)
);

-- 主订单
CREATE TABLE IF NOT EXISTS t_order (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id         VARCHAR(64)   NOT NULL DEFAULT 'global',
    order_no          VARCHAR(64)   NOT NULL,
    idempotency_key   VARCHAR(128)  NOT NULL,
    order_source      VARCHAR(32)   NOT NULL,
    total_amount      NUMERIC(12, 2) NOT NULL DEFAULT 0,
    status            VARCHAR(32)   NOT NULL,
    fulfillment_status VARCHAR(32)  NOT NULL DEFAULT 'PENDING',
    pay_channel       VARCHAR(32),
    pay_trade_no      VARCHAR(64),
    paid_at           TIMESTAMP,
    cancelled_at      TIMESTAMP,
    close_reason      VARCHAR(32),
    recipient_name    VARCHAR(64)   NOT NULL,
    recipient_phone   VARCHAR(20)   NOT NULL,
    detailed_address  VARCHAR(512)  NOT NULL,
    remark            VARCHAR(255),
    created_at        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_t_order_no UNIQUE (order_no),
    CONSTRAINT uk_t_order_idempotency UNIQUE (tenant_id, idempotency_key)
);

CREATE INDEX IF NOT EXISTS idx_t_order_tenant_created
    ON t_order (tenant_id, created_at);

-- 订单明细
CREATE TABLE IF NOT EXISTS t_order_item (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no    VARCHAR(64)    NOT NULL,
    sku_id      BIGINT         NOT NULL,
    quantity    INT            NOT NULL,
    unit_price  NUMERIC(12, 2) NOT NULL,
    subtotal    NUMERIC(12, 2) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_t_order_item_order_no
    ON t_order_item (order_no);

-- Outbox 发件箱
CREATE TABLE IF NOT EXISTS t_outbox_event (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       VARCHAR(64)  NOT NULL DEFAULT 'global',
    aggregate_type  VARCHAR(32)  NOT NULL,
    aggregate_id    VARCHAR(64)  NOT NULL,
    event_type      VARCHAR(64)  NOT NULL,
    payload         TEXT,
    status          VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    retry_count     INT          NOT NULL DEFAULT 0,
    claimed_at      TIMESTAMP,
    lease_until     TIMESTAMP,
    instance_id     VARCHAR(64),
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_t_outbox_status_created
    ON t_outbox_event (status, created_at);

-- 租户元数据表
CREATE TABLE IF NOT EXISTS t_tenant (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   VARCHAR(64)  NOT NULL,
    name        VARCHAR(128) NOT NULL,
    region      VARCHAR(255),
    status      VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_t_tenant_id UNIQUE (tenant_id)
);

-- 用户/账号表
CREATE TABLE IF NOT EXISTS t_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     VARCHAR(64)  NOT NULL,
    username      VARCHAR(64)  NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    display_name  VARCHAR(64)  NOT NULL,
    role          VARCHAR(32)  NOT NULL,
    phone         VARCHAR(20),
    status        VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    must_change_password BOOLEAN   NOT NULL DEFAULT FALSE,
    password_updated_at  TIMESTAMP,
    last_login_at        TIMESTAMP,
    disabled_at          TIMESTAMP,
    disabled_reason      VARCHAR(255),
    failed_login_count   INT       NOT NULL DEFAULT 0,
    locked_until         TIMESTAMP,
    created_by           VARCHAR(64),
    updated_at           TIMESTAMP,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_t_user_username UNIQUE (username)
);

CREATE INDEX IF NOT EXISTS idx_t_user_tenant
    ON t_user (tenant_id);

-- 政府/平台管理员授权范围表（GOVERNMENT 可读区域/租户范围）
CREATE TABLE IF NOT EXISTS t_gov_scope (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   VARCHAR(64)  NOT NULL DEFAULT 'global',
    user_id     BIGINT       NOT NULL,
    scope_type  VARCHAR(32)  NOT NULL,
    scope_value VARCHAR(128) NOT NULL,
    granted_by  VARCHAR(64),
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_t_gov_scope UNIQUE (user_id, scope_type, scope_value)
);

-- 审计日志表
CREATE TABLE IF NOT EXISTS t_audit_log (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id      VARCHAR(64)  NOT NULL DEFAULT 'global',
    actor_user_id  BIGINT,
    actor_username VARCHAR(64),
    actor_role     VARCHAR(32),
    action         VARCHAR(64)  NOT NULL,
    target_type    VARCHAR(64),
    target_id      VARCHAR(128),
    detail         VARCHAR(1024),
    request_id     VARCHAR(64),
    result         VARCHAR(16)  NOT NULL DEFAULT 'SUCCESS',
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 租户元数据安全扩展（区域/类型标识，用于政府聚合范围解析）
ALTER TABLE t_tenant ADD COLUMN IF NOT EXISTS tenant_type VARCHAR(32) NOT NULL DEFAULT 'VILLAGE';
ALTER TABLE t_tenant ADD COLUMN IF NOT EXISTS parent_region VARCHAR(128);

-- ============================================================
-- Flyway V6 等价演进（H2 方言：ADD COLUMN IF NOT EXISTS）
-- 商品域完善（非媒体）+ 订单物流/查询凭证 + 商家资料
-- ============================================================
ALTER TABLE t_product_sku ADD COLUMN IF NOT EXISTS category    VARCHAR(64);
ALTER TABLE t_product_sku ADD COLUMN IF NOT EXISTS unit        VARCHAR(16);
ALTER TABLE t_product_sku ADD COLUMN IF NOT EXISTS origin      VARCHAR(128);
ALTER TABLE t_product_sku ADD COLUMN IF NOT EXISTS detail      TEXT;
ALTER TABLE t_product_sku ADD COLUMN IF NOT EXISTS stock_alert INT NOT NULL DEFAULT 0;
ALTER TABLE t_product_sku ADD COLUMN IF NOT EXISTS created_by  VARCHAR(64);
ALTER TABLE t_product_sku ADD COLUMN IF NOT EXISTS updated_at  TIMESTAMP;

CREATE INDEX IF NOT EXISTS idx_t_product_sku_alert
    ON t_product_sku (tenant_id, status, stock);

ALTER TABLE t_order ADD COLUMN IF NOT EXISTS carrier          VARCHAR(64);
ALTER TABLE t_order ADD COLUMN IF NOT EXISTS tracking_no      VARCHAR(64);
ALTER TABLE t_order ADD COLUMN IF NOT EXISTS shipped_at       TIMESTAMP;
ALTER TABLE t_order ADD COLUMN IF NOT EXISTS cancel_reason    VARCHAR(255);
ALTER TABLE t_order ADD COLUMN IF NOT EXISTS query_token_hash VARCHAR(128);

CREATE INDEX IF NOT EXISTS idx_t_order_tracking
    ON t_order (tenant_id, tracking_no);

CREATE TABLE IF NOT EXISTS t_merchant_profile (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     VARCHAR(64)  NOT NULL,
    shop_slug     VARCHAR(64)  NOT NULL,
    shop_name     VARCHAR(128) NOT NULL,
    contact_name  VARCHAR(64),
    contact_phone VARCHAR(20),
    address       VARCHAR(255),
    intro         VARCHAR(512),
    status        VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP,
    CONSTRAINT uk_t_merchant_profile_tenant UNIQUE (tenant_id),
    CONSTRAINT uk_t_merchant_profile_slug   UNIQUE (shop_slug)
);

