-- ============================================================
-- 智汇于庄 backend · H2（PostgreSQL 兼容模式）测试表结构
-- 与 src/main/resources/db/schema.sql 语义保持一致，仅做方言裁剪：
--   * 不包含 PostgreSQL 专有的 COMMENT ON 语句；
--   * 标识列 / NUMERIC / TEXT / TIMESTAMP 均被 H2 2.x 原生支持。
-- 全部使用 CREATE TABLE IF NOT EXISTS，保证多测试上下文复用同一
-- 内存库（DB_CLOSE_DELAY=-1）时重复初始化不报错。
-- ============================================================

-- 商品 SKU 与库存（CAS 乐观锁扣减目标表）
CREATE TABLE IF NOT EXISTS t_product_sku (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   VARCHAR(64)  NOT NULL DEFAULT 'global',
    sku_code    VARCHAR(64)  NOT NULL,
    spu_name    VARCHAR(255) NOT NULL,
    price       NUMERIC(12, 2) NOT NULL DEFAULT 0,
    stock       INT          NOT NULL DEFAULT 0,
    version     INT          NOT NULL DEFAULT 0,
    status      VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_t_product_sku_tenant_code UNIQUE (tenant_id, sku_code)
);

-- 主订单
CREATE TABLE IF NOT EXISTS t_order (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id         VARCHAR(64)   NOT NULL DEFAULT 'global',
    order_no          VARCHAR(64)   NOT NULL,
    idempotency_key   VARCHAR(128)  NOT NULL,
    order_source      VARCHAR(32)   NOT NULL,
    total_amount      NUMERIC(12, 2) NOT NULL DEFAULT 0,
    status            VARCHAR(32)   NOT NULL,
    fulfillment_status VARCHAR(32)  NOT NULL DEFAULT 'PENDING',
    pay_channel       VARCHAR(32),
    pay_trade_no      VARCHAR(64),
    paid_at           TIMESTAMP,
    cancelled_at      TIMESTAMP,
    close_reason      VARCHAR(32),
    recipient_name    VARCHAR(64)   NOT NULL,
    recipient_phone   VARCHAR(20)   NOT NULL,
    detailed_address  VARCHAR(512)  NOT NULL,
    remark            VARCHAR(255),
    created_at        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_t_order_no UNIQUE (order_no),
    CONSTRAINT uk_t_order_idempotency UNIQUE (tenant_id, idempotency_key)
);

CREATE INDEX IF NOT EXISTS idx_t_order_tenant_created
    ON t_order (tenant_id, created_at);

-- 订单明细
CREATE TABLE IF NOT EXISTS t_order_item (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no    VARCHAR(64)    NOT NULL,
    sku_id      BIGINT         NOT NULL,
    quantity    INT            NOT NULL,
    unit_price  NUMERIC(12, 2) NOT NULL,
    subtotal    NUMERIC(12, 2) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_t_order_item_order_no
    ON t_order_item (order_no);

-- Outbox 发件箱
CREATE TABLE IF NOT EXISTS t_outbox_event (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       VARCHAR(64)  NOT NULL DEFAULT 'global',
    aggregate_type  VARCHAR(32)  NOT NULL,
    aggregate_id    VARCHAR(64)  NOT NULL,
    event_type      VARCHAR(64)  NOT NULL,
    payload         TEXT,
    status          VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    retry_count     INT          NOT NULL DEFAULT 0,
    claimed_at      TIMESTAMP,
    lease_until     TIMESTAMP,
    instance_id     VARCHAR(64),
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_t_outbox_status_created
    ON t_outbox_event (status, created_at);

-- 租户元数据表
CREATE TABLE IF NOT EXISTS t_tenant (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   VARCHAR(64)  NOT NULL,
    name        VARCHAR(128) NOT NULL,
    region      VARCHAR(255),
    status      VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_t_tenant_id UNIQUE (tenant_id)
);

-- 用户/账号表
CREATE TABLE IF NOT EXISTS t_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     VARCHAR(64)  NOT NULL,
    username      VARCHAR(64)  NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    display_name  VARCHAR(64)  NOT NULL,
    role          VARCHAR(32)  NOT NULL,
    phone         VARCHAR(20),
    status        VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_t_user_username UNIQUE (username)
);

CREATE INDEX IF NOT EXISTS idx_t_user_tenant
    ON t_user (tenant_id);
