-- ============================================================
-- Flyway V5 · 政府/平台授权范围与租户区域元数据（阶段 B）
--
-- 背景：VILLAGE 不能等同政府账号。新增 GOVERNMENT 只读角色，其可访问的
-- 行政区域/租户集合由 t_gov_scope 显式授权；平台管理员按 tenant_type 区分
-- 村/合作社/区域。所有聚合查询据此推导数据范围，绝不信任请求头 tenantId。
--
-- 幂等：CREATE TABLE IF NOT EXISTS / ADD COLUMN IF NOT EXISTS，可重复执行。
-- ============================================================

CREATE TABLE IF NOT EXISTS t_gov_scope (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   VARCHAR(64)  NOT NULL DEFAULT 'global',
    user_id     BIGINT       NOT NULL,
    scope_type  VARCHAR(32)  NOT NULL,
    scope_value VARCHAR(128) NOT NULL,
    granted_by  VARCHAR(64),
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_t_gov_scope_user_scope UNIQUE (user_id, scope_type, scope_value)
);

CREATE INDEX IF NOT EXISTS idx_t_gov_scope_user
    ON t_gov_scope (user_id);

COMMENT ON TABLE  t_gov_scope             IS '政府/平台账号数据授权范围（区域/租户集合）';
COMMENT ON COLUMN t_gov_scope.scope_type  IS '范围类型：REGION（行政区域）/ TENANT（租户）/ ALL';
COMMENT ON COLUMN t_gov_scope.scope_value IS '范围取值：区域名或 tenant_id；ALL 类型用 *';
COMMENT ON COLUMN t_gov_scope.granted_by  IS '授权操作人（平台管理员）';

ALTER TABLE t_tenant ADD COLUMN IF NOT EXISTS tenant_type   VARCHAR(32) NOT NULL DEFAULT 'VILLAGE';
ALTER TABLE t_tenant ADD COLUMN IF NOT EXISTS parent_region VARCHAR(128);

COMMENT ON COLUMN t_tenant.tenant_type   IS '租户类型：VILLAGE 村 / COOPERATIVE 合作社 / PLATFORM 平台';
COMMENT ON COLUMN t_tenant.parent_region IS '上级行政区域（用于政府聚合范围解析）';

-- 审计日志表（阶段 B/D/C 通用：管理操作、政府下钻、导出）
CREATE TABLE IF NOT EXISTS t_audit_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id    VARCHAR(64)  NOT NULL DEFAULT 'global',
    actor_user_id BIGINT,
    actor_username VARCHAR(64),
    actor_role   VARCHAR(32),
    action       VARCHAR(64)  NOT NULL,
    target_type  VARCHAR(64),
    target_id    VARCHAR(128),
    detail       VARCHAR(1024),
    request_id   VARCHAR(64),
    result       VARCHAR(16)  NOT NULL DEFAULT 'SUCCESS',
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_t_audit_log_created
    ON t_audit_log (created_at);
CREATE INDEX IF NOT EXISTS idx_t_audit_log_tenant
    ON t_audit_log (tenant_id, created_at);

COMMENT ON TABLE  t_audit_log          IS '操作审计日志（管理/治理/导出/审批）';
COMMENT ON COLUMN t_audit_log.action   IS '动作：TENANT_CREATE/USER_DISABLE/GOV_EXPORT 等';
COMMENT ON COLUMN t_audit_log.result   IS '结果：SUCCESS/FAILED';
