-- ============================================================
-- Flyway V6 · 商品域完善（非媒体部分）+ 订单物流/查询凭证 + 商家资料
--
-- 范围说明（阶段 C/D/E 的非支付、非媒体部分）：
--   * 商品：分类/单位/产地/详情、库存预警阈值、创建人/更新时间
--     （媒体列不在本迁移范围：图片/视频对象存储按约定延后）；
--   * 订单：承运商/物流单号/发货时间、取消原因、本人订单查询凭证哈希；
--   * 商家资料：店铺公开 slug（供匿名下单/公开详情受控解析租户）。
--
-- 幂等：ADD COLUMN IF NOT EXISTS / CREATE TABLE IF NOT EXISTS / CREATE INDEX IF NOT EXISTS。
-- 向后兼容：新列均可空或带默认值，历史订单快照与既有 138 个测试不受影响。
-- ============================================================

-- ---------------- 商品域 ----------------
ALTER TABLE t_product_sku ADD COLUMN IF NOT EXISTS category     VARCHAR(64);
ALTER TABLE t_product_sku ADD COLUMN IF NOT EXISTS unit         VARCHAR(16);
ALTER TABLE t_product_sku ADD COLUMN IF NOT EXISTS origin       VARCHAR(128);
ALTER TABLE t_product_sku ADD COLUMN IF NOT EXISTS detail       TEXT;
ALTER TABLE t_product_sku ADD COLUMN IF NOT EXISTS stock_alert  INT NOT NULL DEFAULT 0;
ALTER TABLE t_product_sku ADD COLUMN IF NOT EXISTS created_by   VARCHAR(64);
ALTER TABLE t_product_sku ADD COLUMN IF NOT EXISTS updated_at   TIMESTAMP;

COMMENT ON COLUMN t_product_sku.category    IS '商品分类（如 GRAIN_OIL 粮油 / FRUIT 果蔬 / OTHER 其他）';
COMMENT ON COLUMN t_product_sku.unit        IS '计量单位（件/袋/箱/斤等）';
COMMENT ON COLUMN t_product_sku.origin      IS '产地（如 河南省周口市鹿邑县试量镇于庄村）';
COMMENT ON COLUMN t_product_sku.detail      IS '商品详情（纯文本；富文本/媒体按约定延后）';
COMMENT ON COLUMN t_product_sku.stock_alert IS '库存预警阈值（stock <= 阈值 时进入预警列表）';
COMMENT ON COLUMN t_product_sku.created_by  IS '创建人用户名';
COMMENT ON COLUMN t_product_sku.updated_at  IS '最近更新时间';

CREATE INDEX IF NOT EXISTS idx_t_product_sku_alert
    ON t_product_sku (tenant_id, status, stock);

-- ---------------- 订单物流与查询凭证 ----------------
ALTER TABLE t_order ADD COLUMN IF NOT EXISTS carrier     VARCHAR(64);
ALTER TABLE t_order ADD COLUMN IF NOT EXISTS tracking_no VARCHAR(64);
ALTER TABLE t_order ADD COLUMN IF NOT EXISTS shipped_at  TIMESTAMP;
ALTER TABLE t_order ADD COLUMN IF NOT EXISTS cancel_reason VARCHAR(255);
ALTER TABLE t_order ADD COLUMN IF NOT EXISTS query_token_hash VARCHAR(128);

COMMENT ON COLUMN t_order.carrier          IS '承运商（发货时填写，如 顺丰/中通/邮政）';
COMMENT ON COLUMN t_order.tracking_no      IS '物流单号（发货时填写）';
COMMENT ON COLUMN t_order.shipped_at       IS '发货时间';
COMMENT ON COLUMN t_order.cancel_reason    IS '取消原因（用户取消/超时关单等补充说明）';
COMMENT ON COLUMN t_order.query_token_hash IS '本人订单查询凭证的 PBKDF2 哈希（下单时下发一次性凭证）';

CREATE INDEX IF NOT EXISTS idx_t_order_tracking
    ON t_order (tenant_id, tracking_no);

-- ---------------- 商家资料（公开店铺解析） ----------------
CREATE TABLE IF NOT EXISTS t_merchant_profile (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id    VARCHAR(64)  NOT NULL,
    shop_slug    VARCHAR(64)  NOT NULL,
    shop_name    VARCHAR(128) NOT NULL,
    contact_name VARCHAR(64),
    contact_phone VARCHAR(20),
    address      VARCHAR(255),
    intro        VARCHAR(512),
    status       VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP,
    CONSTRAINT uk_t_merchant_profile_tenant UNIQUE (tenant_id),
    CONSTRAINT uk_t_merchant_profile_slug   UNIQUE (shop_slug)
);

COMMENT ON TABLE  t_merchant_profile       IS '商家/店铺资料（含公开 slug，供匿名下单与公开详情受控解析租户）';
COMMENT ON COLUMN t_merchant_profile.shop_slug IS '公开店铺标识（URL 友好；匿名请求用它解析租户，替代可伪造的 X-Tenant-Id）';
COMMENT ON COLUMN t_merchant_profile.status   IS '状态：ACTIVE 营业 / DISABLED 停业';
