-- ============================================================
-- 智汇于庄 backend · PostgreSQL 领域表结构（下单交易闭环）
--
-- 设计说明：
--  1. 主键使用标准 SQL 标识列 GENERATED BY DEFAULT AS IDENTITY，
--     PostgreSQL 10+ 与 H2(PostgreSQL 模式) 均兼容，避免 SERIAL 方言差异；
--  2. 订单幂等通过 (tenant_id, idempotency_key) 组合唯一索引兜底，
--     即便并发线程同时通过前置检查，也由数据库唯一约束拦截重复落单；
--  3. 为保持 Outbox / 库存 / 订单的解耦与演进自由度，不建物理外键，
--     由应用层事务 + 唯一索引保证一致性（符合微服务/中台实践）；
--  4. 库存扣减使用应用层 CAS（UPDATE ... WHERE id=? AND stock>=?），
--     表内 version 字段用于审计/重试增强，不依赖数据库触发器。
-- ============================================================

-- 商品 SKU 与库存（CAS 乐观锁扣减目标表）
CREATE TABLE IF NOT EXISTS t_product_sku (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   VARCHAR(64)  NOT NULL DEFAULT 'global',
    sku_code    VARCHAR(64)  NOT NULL,
    spu_name    VARCHAR(255) NOT NULL,
    price       NUMERIC(12, 2) NOT NULL DEFAULT 0,
    stock       INT          NOT NULL DEFAULT 0,
    version     INT          NOT NULL DEFAULT 0,
    status      VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_t_product_sku_tenant_code UNIQUE (tenant_id, sku_code)
);

COMMENT ON TABLE  t_product_sku            IS '商品 SKU（含实时可售库存，CAS 防超卖）';
COMMENT ON COLUMN t_product_sku.version    IS '乐观锁版本号（随 CAS 扣减自增，供审计）';
COMMENT ON COLUMN t_product_sku.status     IS '状态：ACTIVE 在售 / INACTIVE 下架';

-- 主订单（幂等键唯一约束 + 渠道来源 + 收货信息）
CREATE TABLE IF NOT EXISTS t_order (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id         VARCHAR(64)   NOT NULL DEFAULT 'global',
    order_no          VARCHAR(64)   NOT NULL,
    idempotency_key   VARCHAR(128)  NOT NULL,
    order_source      VARCHAR(32)   NOT NULL,
    total_amount      NUMERIC(12, 2) NOT NULL DEFAULT 0,
    status            VARCHAR(32)   NOT NULL,
    recipient_name    VARCHAR(64)   NOT NULL,
    recipient_phone   VARCHAR(20)   NOT NULL,
    detailed_address  VARCHAR(512)  NOT NULL,
    remark            VARCHAR(255),
    created_at        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_t_order_no UNIQUE (order_no),
    CONSTRAINT uk_t_order_idempotency UNIQUE (tenant_id, idempotency_key)
);

CREATE INDEX IF NOT EXISTS idx_t_order_tenant_created
    ON t_order (tenant_id, created_at);

COMMENT ON TABLE  t_order                      IS '特产主订单';
COMMENT ON COLUMN t_order.order_source         IS '订单渠道来源：H5_PRIVATE/DOUYIN/KUAISHOU/B2B_PORTAL';
COMMENT ON COLUMN t_order.idempotency_key      IS '渠道/前端幂等键（与 tenant_id 联合唯一）';
COMMENT ON COLUMN t_order.status               IS '订单状态：PENDING_PAY/STOCK_CONFIRMED/PROCESSING 等';

-- 订单明细（下单商品行快照）
CREATE TABLE IF NOT EXISTS t_order_item (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no    VARCHAR(64)    NOT NULL,
    sku_id      BIGINT         NOT NULL,
    quantity    INT            NOT NULL,
    unit_price  NUMERIC(12, 2) NOT NULL,
    subtotal    NUMERIC(12, 2) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_t_order_item_order_no
    ON t_order_item (order_no);

COMMENT ON TABLE t_order_item IS '订单明细（单价/小计为落单时点快照，防止后续改价影响）';

-- Outbox 发件箱（订单事件与订单主表同事务落库，保证可靠投递）
CREATE TABLE IF NOT EXISTS t_outbox_event (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       VARCHAR(64)  NOT NULL DEFAULT 'global',
    aggregate_type  VARCHAR(32)  NOT NULL,
    aggregate_id    VARCHAR(64)  NOT NULL,
    event_type      VARCHAR(64)  NOT NULL,
    payload         TEXT,
    status          VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    retry_count     INT          NOT NULL DEFAULT 0,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_t_outbox_status_created
    ON t_outbox_event (status, created_at);

COMMENT ON TABLE  t_outbox_event              IS 'Outbox 发件箱（可靠事件投递）';
COMMENT ON COLUMN t_outbox_event.aggregate_type IS '聚合类型：ORDER';
COMMENT ON COLUMN t_outbox_event.aggregate_id   IS '聚合标识：order_no';
COMMENT ON COLUMN t_outbox_event.event_type     IS '事件类型：ORDER_CREATED';
COMMENT ON COLUMN t_outbox_event.payload        IS '事件 JSON 载荷';
COMMENT ON COLUMN t_outbox_event.status         IS '投递状态：PENDING/SENT/FAILED';
COMMENT ON COLUMN t_outbox_event.retry_count    IS '已重试次数';

-- ============================================================
-- 认证 / 多租户元数据（JWT 登录 · 用户与租户维度）
-- ============================================================

-- 租户元数据表（一村/一合作社一租户）
CREATE TABLE IF NOT EXISTS t_tenant (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   VARCHAR(64)  NOT NULL,
    name        VARCHAR(128) NOT NULL,
    region      VARCHAR(255),
    status      VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_t_tenant_id UNIQUE (tenant_id)
);

COMMENT ON TABLE  t_tenant           IS '多租户元数据（一村/一合作社一租户）';
COMMENT ON COLUMN t_tenant.status    IS '状态：ACTIVE 启用 / DISABLED 停用';

-- 用户/账号表（农户 / 合作社 / 村委，按租户隔离）
CREATE TABLE IF NOT EXISTS t_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     VARCHAR(64)  NOT NULL,
    username      VARCHAR(64)  NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    display_name  VARCHAR(64)  NOT NULL,
    role          VARCHAR(32)  NOT NULL,
    phone         VARCHAR(20),
    status        VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_t_user_username UNIQUE (username)
);

CREATE INDEX IF NOT EXISTS idx_t_user_tenant
    ON t_user (tenant_id);

COMMENT ON TABLE  t_user                IS '用户/账号（农户/合作社/村委，按租户隔离）';
COMMENT ON COLUMN t_user.password_hash  IS 'PBKDF2WithHmacSHA256 密码哈希';
COMMENT ON COLUMN t_user.role           IS '角色：FARMER/COOPERATIVE/VILLAGE';
COMMENT ON COLUMN t_user.status         IS '状态：ACTIVE 启用 / DISABLED 停用';
